// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sender: __t.identity(),
  channelId: __t.option(__t.u64()).name("channel_id"),
  threadId: __t.option(__t.u64()).name("thread_id"),
  text: __t.string(),
  sent: __t.timestamp(),
  editedAt: __t.option(__t.timestamp()).name("edited_at"),
});
