// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  channelId: __t.option(__t.u64()).name("channel_id"),
  name: __t.string(),
  color: __t.option(__t.string()),
  permissions: __t.u64(),
  position: __t.u64(),
  createdAt: __t.timestamp().name("created_at"),
  createdBy: __t.option(__t.identity()).name("created_by"),
});
