// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActiveSession = __t.object("ActiveSession", {
  sessionIdentity: __t.identity(),
  connectedAt: __t.timestamp(),
});
export type ActiveSession = __Infer<typeof ActiveSession>;

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.option(__t.string()),
  type: __t.string(),
  createdAt: __t.timestamp(),
  createdBy: __t.option(__t.identity()),
});
export type Channel = __Infer<typeof Channel>;

export const ChannelMember = __t.object("ChannelMember", {
  id: __t.u64(),
  channelId: __t.u64(),
  userId: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type ChannelMember = __Infer<typeof ChannelMember>;

export const EmailCredential = __t.object("EmailCredential", {
  email: __t.string(),
  passwordHash: __t.string(),
  identity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type EmailCredential = __Infer<typeof EmailCredential>;

export const GoogleAuth = __t.object("GoogleAuth", {
  googleId: __t.string(),
  identity: __t.identity(),
  email: __t.option(__t.string()),
  name: __t.option(__t.string()),
  avatar: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type GoogleAuth = __Infer<typeof GoogleAuth>;

export const IdentityLink = __t.object("IdentityLink", {
  sessionIdentity: __t.identity(),
  accountIdentity: __t.identity(),
  linkedAt: __t.timestamp(),
});
export type IdentityLink = __Infer<typeof IdentityLink>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  sender: __t.identity(),
  channelId: __t.option(__t.u64()),
  threadId: __t.option(__t.u64()),
  text: __t.string(),
  sent: __t.timestamp(),
  editedAt: __t.option(__t.timestamp()),
});
export type Message = __Infer<typeof Message>;

export const ReplacedIdentity = __t.object("ReplacedIdentity", {
  oldIdentity: __t.identity(),
  newIdentity: __t.identity(),
  replacedAt: __t.timestamp(),
});
export type ReplacedIdentity = __Infer<typeof ReplacedIdentity>;

export const Role = __t.object("Role", {
  id: __t.u64(),
  channelId: __t.option(__t.u64()),
  name: __t.string(),
  color: __t.option(__t.string()),
  permissions: __t.u64(),
  position: __t.u64(),
  createdAt: __t.timestamp(),
  createdBy: __t.option(__t.identity()),
});
export type Role = __Infer<typeof Role>;

export const RoleMember = __t.object("RoleMember", {
  id: __t.u64(),
  roleId: __t.u64(),
  userId: __t.identity(),
  assignedAt: __t.timestamp(),
  assignedBy: __t.option(__t.identity()),
});
export type RoleMember = __Infer<typeof RoleMember>;

export const Thread = __t.object("Thread", {
  id: __t.u64(),
  channelId: __t.u64(),
  name: __t.string(),
  createdAt: __t.timestamp(),
  createdBy: __t.option(__t.identity()),
});
export type Thread = __Infer<typeof Thread>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
  avatar: __t.option(__t.string()),
  authMethod: __t.option(__t.string()),
  lastIpAddress: __t.option(__t.string()),
});
export type User = __Infer<typeof User>;

export const VoiceParticipant = __t.object("VoiceParticipant", {
  id: __t.u64(),
  roomId: __t.u64(),
  userId: __t.identity(),
  muted: __t.bool(),
  deafened: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type VoiceParticipant = __Infer<typeof VoiceParticipant>;

export const VoiceRecordingChunk = __t.object("VoiceRecordingChunk", {
  id: __t.u64(),
  roomId: __t.u64(),
  channelId: __t.u64(),
  chunkIndex: __t.u64(),
  dataBase64: __t.string(),
  recordedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type VoiceRecordingChunk = __Infer<typeof VoiceRecordingChunk>;

export const VoiceRoom = __t.object("VoiceRoom", {
  id: __t.u64(),
  channelId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type VoiceRoom = __Infer<typeof VoiceRoom>;

export const VoiceSignaling = __t.object("VoiceSignaling", {
  id: __t.u64(),
  roomId: __t.u64(),
  fromUserId: __t.identity(),
  toUserId: __t.identity(),
  signalType: __t.string(),
  signalData: __t.string(),
  createdAt: __t.timestamp(),
});
export type VoiceSignaling = __Infer<typeof VoiceSignaling>;

