// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.option(__t.string()),
  type: __t.string(),
  createdAt: __t.timestamp(),
  createdBy: __t.option(__t.identity()),
});
export type Channel = __Infer<typeof Channel>;

export const ChannelMember = __t.object("ChannelMember", {
  id: __t.u64(),
  channelId: __t.u64(),
  userId: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type ChannelMember = __Infer<typeof ChannelMember>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  sender: __t.identity(),
  channelId: __t.option(__t.u64()),
  threadId: __t.option(__t.u64()),
  text: __t.string(),
  sent: __t.timestamp(),
  editedAt: __t.option(__t.timestamp()),
});
export type Message = __Infer<typeof Message>;

export const Role = __t.object("Role", {
  id: __t.u64(),
  channelId: __t.option(__t.u64()),
  name: __t.string(),
  color: __t.option(__t.string()),
  permissions: __t.u64(),
  position: __t.u64(),
  createdAt: __t.timestamp(),
  createdBy: __t.option(__t.identity()),
});
export type Role = __Infer<typeof Role>;

export const RoleMember = __t.object("RoleMember", {
  id: __t.u64(),
  roleId: __t.u64(),
  userId: __t.identity(),
  assignedAt: __t.timestamp(),
  assignedBy: __t.option(__t.identity()),
});
export type RoleMember = __Infer<typeof RoleMember>;

export const Thread = __t.object("Thread", {
  id: __t.u64(),
  channelId: __t.u64(),
  name: __t.string(),
  createdAt: __t.timestamp(),
  createdBy: __t.option(__t.identity()),
});
export type Thread = __Infer<typeof Thread>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
  avatar: __t.option(__t.string()),
  authMethod: __t.option(__t.string()),
  lastSeenAt: __t.option(__t.timestamp()),
});
export type User = __Infer<typeof User>;

export const UserReportedIp = __t.object("UserReportedIp", {
  identity: __t.identity(),
  ip: __t.string(),
});
export type UserReportedIp = __Infer<typeof UserReportedIp>;

export const UserReportedIpForAdmin = __t.object("UserReportedIpForAdmin", {});
export type UserReportedIpForAdmin = __Infer<typeof UserReportedIpForAdmin>;

export const UserReportedIpRow = __t.object("UserReportedIpRow", {
  identity: __t.identity(),
  ip: __t.string(),
});
export type UserReportedIpRow = __Infer<typeof UserReportedIpRow>;

export const VoiceParticipant = __t.object("VoiceParticipant", {
  id: __t.u64(),
  roomId: __t.u64(),
  userId: __t.identity(),
  muted: __t.bool(),
  deafened: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type VoiceParticipant = __Infer<typeof VoiceParticipant>;

export const VoiceRoom = __t.object("VoiceRoom", {
  id: __t.u64(),
  channelId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type VoiceRoom = __Infer<typeof VoiceRoom>;

export const VoiceSignaling = __t.object("VoiceSignaling", {
  id: __t.u64(),
  roomId: __t.u64(),
  fromUserId: __t.identity(),
  toUserId: __t.identity(),
  signalType: __t.string(),
  signalData: __t.string(),
  createdAt: __t.timestamp(),
});
export type VoiceSignaling = __Infer<typeof VoiceSignaling>;

