// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  fromUserId: __t.identity().name("from_user_id"),
  toUserId: __t.identity().name("to_user_id"),
  signalType: __t.string().name("signal_type"),
  signalData: __t.string().name("signal_data"),
  createdAt: __t.timestamp().name("created_at"),
});
