// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddUserToChannelReducer from "../add_user_to_channel_reducer";
import AssignRoleReducer from "../assign_role_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import CreateRoleReducer from "../create_role_reducer";
import CreateThreadReducer from "../create_thread_reducer";
import DeleteRoleReducer from "../delete_role_reducer";
import EditMessageReducer from "../edit_message_reducer";
import JoinChannelReducer from "../join_channel_reducer";
import JoinVoiceReducer from "../join_voice_reducer";
import KickUserReducer from "../kick_user_reducer";
import LeaveChannelReducer from "../leave_channel_reducer";
import LeaveVoiceReducer from "../leave_voice_reducer";
import RemoveRoleReducer from "../remove_role_reducer";
import ReportClientIpReducer from "../report_client_ip_reducer";
import SendMessageReducer from "../send_message_reducer";
import SendVoiceSignalReducer from "../send_voice_signal_reducer";
import SetAvatarReducer from "../set_avatar_reducer";
import SetNameReducer from "../set_name_reducer";
import ToggleVoiceDeafenReducer from "../toggle_voice_deafen_reducer";
import ToggleVoiceMuteReducer from "../toggle_voice_mute_reducer";

export type AddUserToChannelParams = __Infer<typeof AddUserToChannelReducer>;
export type AssignRoleParams = __Infer<typeof AssignRoleReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateRoleParams = __Infer<typeof CreateRoleReducer>;
export type CreateThreadParams = __Infer<typeof CreateThreadReducer>;
export type DeleteRoleParams = __Infer<typeof DeleteRoleReducer>;
export type EditMessageParams = __Infer<typeof EditMessageReducer>;
export type JoinChannelParams = __Infer<typeof JoinChannelReducer>;
export type JoinVoiceParams = __Infer<typeof JoinVoiceReducer>;
export type KickUserParams = __Infer<typeof KickUserReducer>;
export type LeaveChannelParams = __Infer<typeof LeaveChannelReducer>;
export type LeaveVoiceParams = __Infer<typeof LeaveVoiceReducer>;
export type RemoveRoleParams = __Infer<typeof RemoveRoleReducer>;
export type ReportClientIpParams = __Infer<typeof ReportClientIpReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SendVoiceSignalParams = __Infer<typeof SendVoiceSignalReducer>;
export type SetAvatarParams = __Infer<typeof SetAvatarReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type ToggleVoiceDeafenParams = __Infer<typeof ToggleVoiceDeafenReducer>;
export type ToggleVoiceMuteParams = __Infer<typeof ToggleVoiceMuteReducer>;

